# Generated by Django 3.0.8 on 2020-08-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scientis',
            new_name='scientist',
        ),
    ]
